server.ssl.key-store=${KEY_LOCATION}
server.ssl.key-store-password=${KEY_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=em
server.ssl.enabled=true
app.jwt.secret=${SECRET_KEY}
app.wechat.appId=${APP_ID}
app.wechat.appSecret=${APP_SECRET}